import jsPDF from "jspdf";
import { autoTable, applyPlugin } from "jspdf-autotable";
import { formatDateTime } from "./downloadHelper.js";

const safeValue = (value) => (value == null ? "" : String(value));

export const generatePDF = ({ title, summary, headers, rows, filename }) => {
  applyPlugin(jsPDF);
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const margin = 40;
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFontSize(18);
  doc.setTextColor(12, 139, 82);
  doc.text("SAATHAPP", margin, 50);
  doc.setFontSize(12);
  doc.setTextColor(102, 102, 102);
  doc.text("Company Name: SaathApp", margin, 70);
  doc.text(`Report: ${title}`, margin, 90);
  doc.text(`Generated by: Admin`, margin, 110);
  doc.text(`Generated at: ${formatDateTime(new Date())}`, margin, 130);

  let startY = 150;
  if (summary && summary.length > 0) {
    doc.setFontSize(11);
    summary.forEach((item, index) => {
      doc.text(`${item.label}: ${safeValue(item.value)}`, margin, startY + index * 16);
    });
    startY += summary.length * 16 + 12;
  }

  autoTable(doc, {
    startY,
    head: [headers],
    body: rows,
    theme: "grid",
    headStyles: { fillColor: [12, 139, 82], textColor: 255, halign: "left" },
    styles: { fontSize: 10, cellPadding: 6 },
    margin: { left: margin, right: margin },
    didDrawPage: (data) => {
      const pageCount = doc.internal.getNumberOfPages();
      doc.setFontSize(10);
      doc.text(`Page ${doc.internal.getCurrentPageInfo().pageNumber} of ${pageCount}`, pageWidth - margin, doc.internal.pageSize.getHeight() - 30, { align: "right" });
      doc.setFontSize(9);
      doc.text("SaathApp • Confidential", margin, doc.internal.pageSize.getHeight() - 30);
    },
  });

  doc.save(filename);
};
